"""SUMD generator for testql echo - creates AI-aware project documentation."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from testql.echo_schemas import ProjectEcho


def generate_sumd(project_echo: ProjectEcho, project_path: Path) -> str:
    """Generate SUMD.md content from project echo.
    
    Args:
        project_echo: Parsed project context from toon + doql
        project_path: Path to the project
        
    Returns:
        str: SUMD markdown content
    """
    project_name = project_echo.system_model.project_name or project_path.name
    version = project_echo.system_model.version or "0.1.0"

    sections: list[list[str]] = [
        _header_section(project_name, version),
        _metadata_section(project_name, version),
        _architecture_section(),
        _doql_declaration_section(project_echo, project_name, version),
        _api_contract_section(project_echo),
        _workflows_table_section(project_echo),
        _configuration_section(project_echo, project_name, version),
        _llm_suggestions_section(project_echo),
    ]

    lines: list[str] = []
    for section in sections:
        lines.extend(section)
    return "\n".join(lines)


def _header_section(project_name: str, version: str) -> list[str]:
    return [
        f"# {project_name.upper()}",
        "",
        f"{project_name} - Project documentation generated by testql echo",
        "",
    ]


def _metadata_section(project_name: str, version: str) -> list[str]:
    return [
        "## Metadata",
        "",
        f"- **name**: `{project_name}`",
        f"- **version**: `{version}`",
        "- **ecosystem**: TESTQL + DOQL + taskfile",
        "",
    ]


def _architecture_section() -> list[str]:
    return [
        "## Architecture",
        "",
        "```",
        "DOQL (source) → taskfile (automation) → testql (verification)",
        "```",
        "",
    ]


def _doql_declaration_section(project_echo: ProjectEcho, project_name: str, version: str) -> list[str]:
    model = project_echo.system_model
    if not model.interfaces and not model.workflows:
        return []

    lines = [
        "### DOQL Application Declaration",
        "",
        "```less",
        "app {",
        f"  name: {project_name};",
        f"  version: {version};",
        "}",
        "",
    ]
    for interface in model.interfaces:
        lines.append(f'interface[type="{interface.type}"] {{')
        if interface.framework:
            lines.append(f"  framework: {interface.framework};")
        lines += ["}", ""]

    for workflow in model.workflows:
        lines.append(f'workflow[name="{workflow.name}"] {{')
        lines.append(f"  trigger: {workflow.trigger};")
        if workflow.cmd:
            lines.append(f"  step-1: run cmd={workflow.cmd};")
        lines += ["}", ""]

    lines += ["```", ""]
    return lines


def _api_contract_section(project_echo: ProjectEcho) -> list[str]:
    if not project_echo.api_contract.endpoints:
        return []

    by_method: dict[str, list[dict]] = {}
    for ep in project_echo.api_contract.endpoints:
        method = ep.get("method", "GET")
        by_method.setdefault(method, []).append(ep)

    lines = ["## API Contract", "", "Generated from testql scenarios:", "", "```toon", "# API Endpoints", ""]
    for method, eps in by_method.items():
        lines.append(f"### {method}")
        lines.append("")
        for ep in eps:
            path = ep.get("path", "/")
            status = ep.get("status", "200")
            desc = ep.get("description", "")
            lines.append(f"- `{path}` → {status}" + (f" # {desc}" if desc else ""))
        lines.append("")
    lines += ["```", ""]
    return lines


def _workflows_table_section(project_echo: ProjectEcho) -> list[str]:
    workflows = project_echo.system_model.workflows
    if not workflows:
        return []

    lines = ["## Workflows", "", "| Workflow | Trigger | Command |", "|----------|---------|---------|"]
    for wf in workflows:
        cmd = wf.cmd or "-"
        if len(cmd) > 40:
            cmd = cmd[:37] + "..."
        lines.append(f"| {wf.name} | {wf.trigger} | `{cmd}` |")
    lines.append("")
    return lines


def _configuration_section(project_echo: ProjectEcho, project_name: str, version: str) -> list[str]:
    lines = [
        "## Configuration", "",
        "```yaml",
        "project:",
        f"  name: {project_name}",
        f"  version: {version}",
        "  env: local",
    ]
    if project_echo.api_contract.base_url:
        lines.append(f"  base_url: {project_echo.api_contract.base_url}")
    lines += ["```", ""]
    return lines


def _llm_suggestions_section(project_echo: ProjectEcho) -> list[str]:
    workflows = project_echo.system_model.workflows
    lines = ["## LLM Suggestions", "", "### Quick Start", ""]

    lines.extend(_workflow_snippet(workflows, "install", "# Setup", "task install"))
    test_wf = next((w for w in workflows if "test" in w.name), None)
    if test_wf:
        lines += ["```bash", "# Run tests", f"task {test_wf.name}", "```", ""]
    lines.extend(_workflow_snippet(workflows, "run", "# Start application", "task run"))

    lines += [
        "### TestQL Commands", "",
        "```bash",
        "# List API endpoints",
        "testql endpoints .",
        "",
        "# Generate OpenAPI spec",
        "testql openapi . --contract-tests",
        "",
        "# Run tests",
        "testql suite",
        "```",
        "",
    ]
    return lines


def _workflow_snippet(workflows: list, name: str, comment: str, cmd: str) -> list[str]:
    wf = next((w for w in workflows if w.name == name), None)
    if wf:
        return ["```bash", comment, cmd, "```", ""]
    return []


def save_sumd(project_echo: ProjectEcho, project_path: Path, output_path: Path | None = None) -> Path:
    """Generate and save SUMD.md file.
    
    Args:
        project_echo: Project context
        project_path: Project directory
        output_path: Optional custom output path
        
    Returns:
        Path to saved file
    """
    content = generate_sumd(project_echo, project_path)
    
    if output_path is None:
        output_path = project_path / "SUMD.md"
    
    output_path.write_text(content, encoding="utf-8")
    return output_path
