"""SUMD generator for testql echo - creates AI-aware project documentation."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from testql.echo_schemas import ProjectEcho


def generate_sumd(project_echo: ProjectEcho, project_path: Path) -> str:
    """Generate SUMD.md content from project echo.
    
    Args:
        project_echo: Parsed project context from toon + doql
        project_path: Path to the project
        
    Returns:
        str: SUMD markdown content
    """
    lines = []
    
    # Header
    project_name = project_echo.system_model.project_name or project_path.name
    version = project_echo.system_model.version or "0.1.0"
    
    lines.append(f"# {project_name.upper()}")
    lines.append("")
    lines.append(f"{project_name} - Project documentation generated by testql echo")
    lines.append("")
    
    # Metadata
    lines.append("## Metadata")
    lines.append("")
    lines.append(f"- **name**: `{project_name}`")
    lines.append(f"- **version**: `{version}`")
    lines.append(f"- **ecosystem**: TESTQL + DOQL + taskfile")
    lines.append("")
    
    # Architecture
    lines.append("## Architecture")
    lines.append("")
    lines.append("```")
    lines.append("DOQL (source) → taskfile (automation) → testql (verification)")
    lines.append("```")
    lines.append("")
    
    # DOQL Application Declaration
    if project_echo.system_model.interfaces or project_echo.system_model.workflows:
        lines.append("### DOQL Application Declaration")
        lines.append("")
        lines.append("```less")
        lines.append(f"app {{")
        lines.append(f"  name: {project_name};")
        lines.append(f"  version: {version};")
        lines.append("}")
        lines.append("")
        
        # Interfaces
        for interface in project_echo.system_model.interfaces:
            lines.append(f'interface[type="{interface.type}"] {{')
            if interface.framework:
                lines.append(f"  framework: {interface.framework};")
            lines.append("}")
            lines.append("")
        
        # Workflows
        for workflow in project_echo.system_model.workflows:
            lines.append(f'workflow[name="{workflow.name}"] {{')
            lines.append(f"  trigger: {workflow.trigger};")
            if workflow.cmd:
                lines.append(f"  step-1: run cmd={workflow.cmd};")
            lines.append("}")
            lines.append("")
        
        lines.append("```")
        lines.append("")
    
    # API Contract from toon tests
    if project_echo.api_contract.endpoints:
        lines.append("## API Contract")
        lines.append("")
        lines.append("Generated from testql scenarios:")
        lines.append("")
        lines.append("```toon")
        lines.append("# API Endpoints")
        lines.append("")
        
        # Group by method
        by_method: dict[str, list[dict]] = {}
        for ep in project_echo.api_contract.endpoints:
            method = ep.get("method", "GET")
            if method not in by_method:
                by_method[method] = []
            by_method[method].append(ep)
        
        for method, endpoints in by_method.items():
            lines.append(f"### {method}")
            lines.append("")
            for ep in endpoints:
                path = ep.get("path", "/")
                status = ep.get("status", "200")
                desc = ep.get("description", "")
                lines.append(f"- `{path}` → {status}" + (f" # {desc}" if desc else ""))
            lines.append("")
        
        lines.append("```")
        lines.append("")
    
    # Workflows
    if project_echo.system_model.workflows:
        lines.append("## Workflows")
        lines.append("")
        lines.append("| Workflow | Trigger | Command |")
        lines.append("|----------|---------|---------|")
        for workflow in project_echo.system_model.workflows:
            cmd = workflow.cmd or "-"
            if len(cmd) > 40:
                cmd = cmd[:37] + "..."
            lines.append(f"| {workflow.name} | {workflow.trigger} | `{cmd}` |")
        lines.append("")
    
    # Configuration
    lines.append("## Configuration")
    lines.append("")
    lines.append("```yaml")
    lines.append("project:")
    lines.append(f"  name: {project_name}")
    lines.append(f"  version: {version}")
    lines.append("  env: local")
    if project_echo.api_contract.base_url:
        lines.append(f"  base_url: {project_echo.api_contract.base_url}")
    lines.append("```")
    lines.append("")
    
    # LLM Suggestions
    lines.append("## LLM Suggestions")
    lines.append("")
    lines.append("### Quick Start")
    lines.append("")
    
    install_wf = next((w for w in project_echo.system_model.workflows if w.name == "install"), None)
    if install_wf:
        lines.append("```bash")
        lines.append("# Setup")
        lines.append("task install")
        lines.append("```")
        lines.append("")
    
    test_wf = next((w for w in project_echo.system_model.workflows if "test" in w.name), None)
    if test_wf:
        lines.append("```bash")
        lines.append("# Run tests")
        lines.append(f"task {test_wf.name}")
        lines.append("```")
        lines.append("")
    
    run_wf = next((w for w in project_echo.system_model.workflows if w.name == "run"), None)
    if run_wf:
        lines.append("```bash")
        lines.append("# Start application")
        lines.append("task run")
        lines.append("```")
        lines.append("")
    
    lines.append("### TestQL Commands")
    lines.append("")
    lines.append("```bash")
    lines.append("# List API endpoints")
    lines.append("testql endpoints .")
    lines.append("")
    lines.append("# Generate OpenAPI spec")
    lines.append("testql openapi . --contract-tests")
    lines.append("")
    lines.append("# Run tests")
    lines.append("testql suite")
    lines.append("```")
    lines.append("")
    
    return "\n".join(lines)


def save_sumd(project_echo: ProjectEcho, project_path: Path, output_path: Path | None = None) -> Path:
    """Generate and save SUMD.md file.
    
    Args:
        project_echo: Project context
        project_path: Project directory
        output_path: Optional custom output path
        
    Returns:
        Path to saved file
    """
    content = generate_sumd(project_echo, project_path)
    
    if output_path is None:
        output_path = project_path / "SUMD.md"
    
    output_path.write_text(content, encoding="utf-8")
    return output_path
