"""Data models for NL → TestQL generation."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass
class Plan:
    project_name: str = "testql"
    version: str = "1.0.0"
    planner: str = "rule-based"

    def to_testql_less(self) -> str:
        return f"""// TestQL manifest generated by nlp2testql
app {{
  name: {self.project_name};
  version: {self.version};
}}

dependencies {{
  runtime: "httpx>=0.27, click>=8.0";
}}

interface[type="cli"] {{
  framework: click;
}}

workflow[name="test"] {{
  trigger: manual;
  step-1: run cmd=echo "Testing...";
}}
"""


@dataclass
class GenerateResult:
    ok: bool
    testql: str
    plan: Plan
    validation: dict[str, Any] | None = None
    output_path: str | None = None
    error: str | None = None
