flowchart TD
    code2llm_output__map["code2llm_output.map<br/>83 funcs"]
    testql___base_fallback["testql._base_fallback<br/>26 funcs"]
    testql__commands["testql.commands<br/>107 funcs"]
    testql__detectors["testql.detectors<br/>53 funcs"]
    testql__generators["testql.generators<br/>43 funcs"]
    testql__interpreter["testql.interpreter<br/>132 funcs"]
    testql__openapi_generator["testql.openapi_generator<br/>21 funcs"]
    testql__runner["testql.runner<br/>18 funcs"]
    testql__commands ==>|13| code2llm_output__map
    testql__commands ==>|5| testql___base_fallback
    testql__interpreter ==>|5| code2llm_output__map
    testql__interpreter -->|3| testql___base_fallback
    testql__generators -->|2| testql___base_fallback
    testql__runner -->|1| code2llm_output__map
    testql__runner -->|1| testql___base_fallback
    testql__openapi_generator -->|1| code2llm_output__map
    testql__openapi_generator -->|1| testql___base_fallback
    testql__generators -->|1| code2llm_output__map
    testql__detectors -->|1| testql___base_fallback
