"""IR → pytest-friendly Python module.

Emits one `def test_<step_name>():` per step, with light comments. The
generated file is intentionally simple — it imports nothing and asserts only
that the step has been declared. Specialised executors can replace the body.
"""

from __future__ import annotations

from dataclasses import dataclass

from testql.ir import ApiStep, GraphqlStep, GuiStep, ProtoStep, SqlStep, Step, TestPlan

from .base import BaseTarget


def _safe_ident(name: str | None, fallback: str) -> str:
    candidate = name or fallback
    out = "".join(c if c.isalnum() else "_" for c in candidate).strip("_").lower()
    return out or "step"


_SUMMARY_BY_TYPE: tuple[tuple[type, "callable"], ...] = (
    (ApiStep, lambda s: f"{s.method} {s.path} (status={s.expect_status})"),
    (SqlStep, lambda s: f"SQL[{s.dialect}]: {s.query}"),
    (ProtoStep, lambda s: f"Proto: {s.message} ({s.check})"),
    (GraphqlStep, lambda s: f"GraphQL[{s.operation}]: {s.body[:40]}…"),
    (GuiStep, lambda s: f"GUI: {s.action} {s.selector or s.path or ''}".strip()),
)


def _step_summary(step: Step) -> str:
    for cls, fn in _SUMMARY_BY_TYPE:
        if isinstance(step, cls):
            return fn(step)
    return f"{step.kind}: {step.name}"


def _emit_test(step: Step, index: int) -> str:
    ident = _safe_ident(step.name, step.kind or f"step_{index}")
    summary = _step_summary(step).replace('"', '\\"')
    return (
        f"def test_{ident}():\n"
        f'    """{summary}"""\n'
        f"    assert True  # generated stub for {step.kind!r}\n"
    )


@dataclass
class PytestTarget(BaseTarget):
    name: str = "pytest"
    file_extension: str = ".py"

    def render(self, plan: TestPlan) -> str:
        header = (
            f'"""Generated from {plan.metadata.name!r} '
            f'(type={plan.metadata.type!r}). Auto-generated by testql.generators."""\n'
            f"\n"
        )
        bodies = [_emit_test(s, i) for i, s in enumerate(plan.steps, start=1)]
        return header + "\n".join(bodies) + ("\n" if bodies else "")


__all__ = ["PytestTarget"]
